public class Main {
    public static void main(String[] args) {
        System.out.println("##################################START#################################");
        System.out.println("Problem 1");
        System.out.println("How do you print duplicate characters from a string? ");
        Duplicate duplicate = new Duplicate();
        duplicate.printAllDuplicate("Deepti Will Find Duplicates!!!");
        System.out.println();
        System.out.println("###################################################################");
        System.out.println("Problem 2");
        System.out.println("How do you check if two strings are anagrams of each other?");
        Sequence anagram = new Sequence();
        String firstString = "stops";
        String secondString = "posts";
        Boolean isAnagram = anagram.checkAnagram(firstString, secondString);
        System.out.println(firstString +" and " +secondString+ " are anagrams :: " +isAnagram);
        System.out.println("###################################################################");
        System.out.println("Problem 3");
        System.out.println("How do you print the first non-repeated character from a string?");
        duplicate.printFirstNonDuplicateChar("aidnkkaw");
        System.out.println("###################################################################");
        System.out.println("Problem 4");
        System.out.println("How can a given string be reversed using recursion?");
        ModifyString reverse = new ModifyString();
        System.out.println(reverse.useRecursionReverse("aidnkkaw"));
        System.out.println("###################################################################");
        System.out.println("Problem 5");
        System.out.println("How do you check if a string contains only digits?");
        Digit digit = new Digit();
        String s1 = "sdlknfg435lks";
        String s2 = "23234645745";
        Boolean isDigitS1 = digit.checkStringForOnlyDigit(s1);
        Boolean isDigitS2 = digit.checkStringForOnlyDigit(s2);
        System.out.println(s1 +" contains only digit ::: " + isDigitS1);
        System.out.println(s2 +" contains only digit ::: " + isDigitS2);
        System.out.println("###################################################################");
        System.out.println("Problem 6");
        System.out.println("How do you count the occurrence of a given character in a string?");
        Occurances occurrencesOfVowelsAndConsonants = new Occurances();
        int[] no = occurrencesOfVowelsAndConsonants.countVowelsAndConsonants("klyhgtfbaiouertyuo");
        System.out.println("Number of vowels are == " + no[0]);
        System.out.println("Number of consonants are == " + no[1]);
        System.out.println("###################################################################");
        System.out.println("Problem 6");
        System.out.println("How do you count a number of vowels and consonants in a given string?");
        Occurances occurancesOfAnyCharacter = new Occurances();
        int noOfOcc = occurancesOfAnyCharacter.countChar("jdkjsdkjsfjsf",'j');
        System.out.println("Number of Occurrences of 'j' are == " + noOfOcc);
        System.out.println("###################################################################");
        System.out.println("Problem 7");
        System.out.println("How do you reverse words in a given sentence without using any library method?");
        ModifyString.reverseSentence("This is our sentence");
        System.out.println("###################################################################");
        System.out.println("Problem 8");
        System.out.println("How do you check if two strings are a rotation of each other?");
        Sequence rotation = new Sequence();
        boolean isRotation = rotation.checkRotation("ThisVsThat", "ThatVsThis");
        System.out.println("Strings are rotations :::: " + isRotation);
        System.out.println("###################################################################");
        System.out.println("Problem 9");
        System.out.println("How do you check if a given string is a palindrome?");
        Sequence palindrome = new Sequence();
        boolean isPalindrome = rotation.checkPalindrome("bbbbbbbb");
        System.out.println("String is Palindrome :::: " + isPalindrome);
        System.out.println("##################################END#################################");
    }
}
